# Base configs
baseurl: "https://glitchinthematrix.github.io/photography"
image_fulls_loc: "/images/fulls"
image_thumbs_loc: "/images/thumbs"

# UI configs
title: "Photography by Bhishma Dedhia"
subtitle: "I like freezing time"
author: "Bhishma Dedhia"
header:
 title: "Photography"
 subtitle: "by Bhishma Dedhia"
footer:
 name: "Hey there, my name is Bhishma"
 bio: "I sometimes capture the world around me."


google_analytics: UA-102623606-2
